apiVersion: v1
kind: Service
metadata:
  name: factorio
  namespace: factorio
spec:
  type: NodePort
  # Include the ExternalTrafficPolicy if you need source IPs.
  # This will require targeting the node the pod is running on.
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: factorio
  ports:
    - name: game
      protocol: UDP
      port: 34197
      targetPort: 34197
      nodePort: 34197
    - name: rcon
      protocol: TCP
      port: 27015
      targetPort: 27015
      nodePort: 27015
