apiVersion: v1
kind: Service
metadata:
  name: factorio
  namespace: factorio
spec:
  selector:
    app.kubernetes.io/name: factorio
  type: NodePort
  ports:
    - protocol: UDP
      port: 34197
      nodePort: 32767
      name: factorio
